services:
  collector-app:
    depends_on:
      postgres: # mysql -> postgres로 변경
        condition: service_healthy
    restart: on-failure # 실패 시 재시작 옵션 추가
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livelihood-coupon-collector-app-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - livelihoodCoupon-net
