services:
  collector-app:
    depends_on:
      postgres:
        condition: service_healthy
      redis: # infra/database/docker-compose.yml에 정의된 redis
        condition: service_healthy
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livelihoodCoupon-collector-app-1
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=local
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - OSRM_CAR_URL=http://osrm-car:5000
      - OSRM_FOOT_URL=http://osrm-foot:5000
      - OSRM_BIKE_URL=http://osrm-bike:5000
      - OSRM_TRANSIT_URL=http://osrm-transit:5000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - livelihoodCoupon-net


networks:
  livelihoodCoupon-net:
    driver: bridge

