kakao:
  api:
    key: ${KAKAO_API_KEY}
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/livelihoodCoupon_db?sslmode=disable&connectTimeout=10&options=-c TimeZone%3DAsia/Seoul
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always # 배치 테이블 자동 생성
  jpa:
    hibernate:
      ddl-auto: update

cors:
  allowed-origins: http://localhost:8081