kakao:
  api:
    key: ${KAKAO_API_KEY}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livelihoodCoupon_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: livelihoodCoupon_user
    password: livelihoodCoupon_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect