services:
  # OSRM 서버 (자동차 경로)
  osrm-car:
    image: osrm/osrm-backend:latest
    container_name: livelihoodCoupon-osrm-car-1
    ports:
      - "5004:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/south-korea-latest.foot.osrm
    # 대신 컨테이너 RAM 제한
    deploy:
      resources:
        limits:
          memory: 16G
    environment:
      - TZ=Asia/Seoul
    networks:
      - livelihoodCoupon-net
    restart: unless-stopped

  # OSRM 서버 (도보 경로)
  osrm-foot:
    image: osrm/osrm-backend:latest
    container_name: livelihoodCoupon-osrm-foot-1
    ports:
      - "5001:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/south-korea-latest.foot.osrm
    # 대신 컨테이너 RAM 제한
    deploy:
      resources:
        limits:
          memory: 16G
    environment:
      - TZ=Asia/Seoul
    networks:
      - livelihoodCoupon-net
    restart: unless-stopped

  # OSRM 서버 (자전거 경로)
  osrm-bike:
    image: osrm/osrm-backend:latest
    container_name: livelihoodCoupon-osrm-bike-1
    ports:
      - "5002:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/south-korea-latest.foot.osrm
    # 대신 컨테이너 RAM 제한
    deploy:
      resources:
        limits:
          memory: 16G
    environment:
      - TZ=Asia/Seoul
    networks:
      - livelihoodCoupon-net
    restart: unless-stopped

networks:
  livelihoodCoupon-net:
    external: true